---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Investigation of '150' MMSI prefix vessels

This repository is designed to identify and describe the activities of vessels 
which are members of a fleet of likely Chinese Squid jiggers. The vessels are characterised
by having and MMSI prefix '150' and consistently changing their name transmitted on 
AIS while operating. Individual vessels in this fleet have been the subject of two
Joint Analytical Cell (JAC) intelligence reports. This analysis aims to investigate and 
escribe the general trends of the fleet. 

## Structure and descriptions

    |- README.md		<- Top-level README on how to use this repo
    |- data			    <- Data files. Create subfolders as necessary.
    |- docs			    <- Documentation.
    |- models		    <- Trained models, model summaries, etc.
    |- notebooks 	    <- Jupyter notebooks and R markdown. Naming convention TBD. Use jupytext to convert
    |				       to .py before committing and do not commit the notebook itself. Suggest having
    |				       subfolders for different subsets of analysis. Could also have different
    |				       subfolders for each person if that makes more sense for your project/team.
    |- outputs		    <- Models results, static reports, etc. Create  additional subfolders as necessary.
    |    |- figures	    <- Create versioned figures folders if desired.
    |- queries		    <- SQL files (.sql, .jinja2, etc). Create subfolders as necessary. When creating
    |				       new tables in BigQuery, be sure to use a schema with good field descriptions.
    |- scripts		    <- Regular python and R files. These may use code from <module> but are not
    |				       notebooks. A good place for scripts that run data pipelines, train models, etc.
    |- .gitignore	    <- Modify as necessary.
    
