---
title: "LU RONG YUAN YU 715"
author: "Max Schofield"
date: "2022-11-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

foo <- function(x){
  for( i in x ){
    #  require returns TRUE invisibly if it was able to load package
    if( ! require( i , character.only = TRUE ) ){
      #  If package was not able to be loaded then re-install
      install.packages( i , dependencies = TRUE )
      #  Load package after installing
      require( i , character.only = TRUE )
    }
  }
}

#  Then try/install packages...
foo( c("tidyverse" , "bigrquery" ,"devtools", "DBI","glue", "lubridate", "here", "sf", "extrafont", "patchwork", "terra", "rnaturalearthhires") )

# get fishwatch r independently 
if (!require("fishwatchr")) {devtools::install_github("GlobalFishingWatch/fishwatchr")}
library(fishwatchr)

# # Get Rnatural resources from https://ropensci.r-universe.dev/ui#packages
# # Enable repository from ropensci
# options(repos = c(
#   ropensci = 'https://ropensci.r-universe.dev',
#   CRAN = 'https://cloud.r-project.org'))
# # Download and install rnaturalearthhires in R
# install.packages('rnaturalearthhires')


if (!require("extrafont"))
  install.packages("extrafont")

# Unfortunately `extrafont::font_import()` will fail on latest Rttf2pt1 package...
# so we need to install old version
devtools::install_version("Rttf2pt1", version = "1.3.8")

# Import fonts to R
# This will take few minutes
extrafont::font_import()

```

```{r con}
con <- DBI::dbConnect(drv = bigrquery::bigquery(), 
                      project = "world-fishing-827", 
                      use_legacy_sql = FALSE)
```


Pull data from research fishing to 

```{r, include=FALSE}
# get track data for plotting 

voi_q <- readr::read_file(file = here::here("queries", ".", "bp_voi_ais_gear_analysis.sql"))



voi_atl <- fishwatchr::gfw_query(query = glue::glue(voi_q, 
                                              date_start = '2022-01-01',
                                              date_end = '2022-01-31', 
                                              voi = '412331284'),
                            run_query = TRUE,
                            con = con)$data


voi_pac <- fishwatchr::gfw_query(query = glue::glue(voi_q, 
                                              date_start = '2022-10-04',
                                              date_end = '2022-10-10', 
                                              voi = '412331284'),
                            run_query = TRUE,
                            con = con)$data

```


```{r, include=FALSE, warning=FALSE}
# try using off the shelf plotting code 


plot_df <- voi_atl %>% filter(between(as.Date(timestamp),as.Date('2022-01-03'),
                                                 as.Date('2022-01-08')))  

# new bounding box buffered 10 degrees
bounding <- transform_box(xlim = c(min(vessel_track$lon) - 0.1,
                                               max(vessel_track$lon) + 0.1),
                                      ylim = c(min(vessel_track$lat) - 0.1,
                                               max(vessel_track$lat) + 0.1),
                                      output_crs = gfw_projections('Equal Earth')$proj)

fishing_track_review(track_df = plot_df,
                     #bounding_box_man = bounding$box_out,
                     color_fishing = FALSE,
                     gfw_proj_name = 'Equal Earth', 
                     globe_location = 'lowerright',
                     time_series_labels = c('speed_knots'),
                     vessel_name = 'LU RONG YUAN YU 715')

# works ok - could be improved. Manual bounding box not working.

# higher zoom on vessel track 
# add EEZ boundaries 
# colour track by speed

```

```{r}
# pull in EEZ shapefile for adding to map

# EEZ shape is too big

# eez <- fishwatchr::gfw_query(query = c('SELECT eezs FROM `world-fishing-827.ocean_shapefiles_all_purpose.all_eezs_union`'),
#                             run_query = TRUE,
#                             con = con)$data
 


```

```{r, include=FALSE, warning=FALSE}
# try dockering back end function components to make a bespoke plot 

# plot time series component to show the vessels speed through time  
plot_df <- voi_atl %>% filter(between(as.Date(timestamp),as.Date('2022-01-18'),
                                                 as.Date('2022-01-24'))) 

# make the time series data in the correct format
ts_plot_df <- plot_df %>%
  dplyr::mutate(next_time = dplyr::lead(timestamp),
                time_diff_hr = as.numeric(difftime(next_time,
                                                   timestamp,
                                                   tz = 'UTC',
                                                   units = 'sec'))/3600,
                next_far = ifelse(time_diff_hr > 3, TRUE, FALSE),
                prev_far = ifelse(lead(next_far) == TRUE, TRUE, FALSE),
                nnet_score = as.character(ifelse(next_far == TRUE | prev_far == TRUE | 
                                                   is.na(nnet_score), 2 , nnet_score)),
                slow_speed = ifelse(speed_knots<5, TRUE, FALSE))

# make the line plot coloured by speed
line_geom <-
  geom_path(data = ts_plot_df,
            aes(x= timestamp,
                #eval(as.symbol(speed_knots)),
                y= speed_knots,
                color = factor(slow_speed),
                size = factor(slow_speed),
                group  = ssvid))
# set colours 
line_colorscale <-
  scale_color_manual('',
                     breaks = c(FALSE,TRUE),
                     values = c('#76ADAD',
                                '#E34D4E',
                                'grey85'),
                     # labels = NULL)
                     labels = c('>5 knots','< 5 knots'))
# set size 
line_sizescale <- scale_size_manual('',
                  breaks = c(TRUE,FALSE),
                  values = c(0.5,0.5,0.3),
                  # labels = NULL)
                  labels = c('>5 knots','< 5 knots'))

# time series plot of speed
time_series_plot <- ggplot() +
  line_geom +
  # point_geom +
  line_sizescale +
  line_colorscale +
  #y_axis +
  scale_x_datetime('\nDate') +
  fishwatchr::theme_gfw() +
  theme(
        legend.position = 'none',
        legend.justification = 'right',
        panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.background = element_rect(fill = '#ffffff'),
        panel.border = element_rect(fill = NA, color = '#000000'),
        plot.background = element_rect(fill = '#ffffff'))+
        # axis.text.x = element_blank(),
        # axis.title.x = element_blank()) +
  labs(y='Speed (knots)')

# make land object at default scale of  10 
land_sf <- rnaturalearth::ne_countries(scale = 10,
                                       returnclass = "sf")

# manual bounding box bounds set to +/- buf 
buf <- 0.1
bounding_box <- transform_box(xlim = c(min(ts_plot_df$lon) - buf,
                                               max(ts_plot_df$lon) + buf),
                                      ylim = c(min(ts_plot_df$lat) - buf,
                                               max(ts_plot_df$lat) + buf),
                                      output_crs = gfw_projections('Equal Earth')$proj)

# make a track object colored by speed 
track_sf <- make_track(ts_plot_df,
                       color_by = 'slow_speed')

# pull out vessel mmsi 
vessel_mmsi <- track_sf %>%
    sf::st_drop_geometry(.) %>%
    dplyr::distinct(ssvid) %>%
    dplyr::pull(ssvid)

# set land to light theme colours 
land_fill = fishwatchr::gfw_palettes$map_country_light[1]
land_color = fishwatchr::gfw_palettes$map_country_light[2]

# set grid colour 
grid_color = 'grey85'

# set vessel track geom based on speed
vessel_track_geom <-
  geom_sf(data = track_sf,
          aes(
            color = slow_speed,
            group = ssvid
          )
      )

# set geom color scale to speed too. 
vessel_track_colorscale <-
  scale_color_manual("",
                     breaks = c(FALSE, TRUE),
                     values = c(
                       "#76ADAD",
                       "#E34D4E",
                       'grey85'
                     ),
                     labels = c(
                       "> 5 knots",
                       "< 5 knots")
                     )

vessel_name <- 'LU RONG YUAN YU 715'

map <- ggplot() +
  geom_sf(
    data = land_sf,
    fill = land_fill,
    color = land_color,
    size = 0.2
  ) +
  vessel_track_geom +
  vessel_track_colorscale +
    geom_gfw_eez(colour='black', lty=2,lwd=1.2, theme ='light', proj = "+proj=eqearth +datum=WGS84 +wktext") +
  coord_sf(
    xlim = c(bounding_box$box_out[["xmin"]], bounding_box$box_out[["xmax"]]),
    ylim = c(bounding_box$box_out[["ymin"]], bounding_box$box_out[["ymax"]]),
    crs = bounding_box$out_crs
  ) +
  fishwatchr::theme_gfw_map(theme = 'light') +
  labs(title = vessel_name,
       subtitle = vessel_mmsi, 
       fill = 'Speed') +
    theme(
    # legend.position = c(1.7,0.2),
    legend.position = 'bottom',
    # legend.position = 'none',
    legend.justification = "right",
    # panel.border = element_rect(fill = NA, color = 'grey15'),
    plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "cm"),
    panel.grid.major = element_line(colour = grid_color,
                                    size = 0.1), 
    plot.title=element_text(size=10),
    plot.subtitle=element_text(size=9)
  ) 

# stacked_timeseries <- stack_timeseries(line_plot_list)
# num_components <- length(line_plot_list)
# height_ratio_list <- list(0.2, 0.3, 0.35, 0.4, 0.5)

num_components <- 1
page_layout <- patchwork::plot_layout(ncol = 1,
                                      # widths = c(1.5,1),
                                      heights = c(1 - 0.3, 0.3),
                                      guides = 'auto')
                                      # guides = 'keep')

# arrange plots on page
fishwatchr::add_little_globe(map,
                             main_box = bounding_box,
                             globe_rel_size = '0.25',
                             globe_just = 'inside',
                             globe_position = 'upperright') +
    time_series_plot +
    page_layout

# map +
#     time_series_plot +
#     page_layout

# setwd('./outputs/figures')
ggsave('../outputs/figures/LU RONG YUAN YU 715_example_Atlantic.png', device='png')


# wrap_plots(fishwatchr::add_little_globe(map,
#                              main_box = bounding_box,
#                              globe_rel_size = '0.25',
#                              globe_just = 'inside',
#                              globe_position = 'upperright'), 
#            time_series_plot, ncol=1, guides='collect')


```

```{r, include=FALSE, warning=FALSE}
# Pacific plotting code

# should build into a function 
# date filtering voi_pac
# plot_df2 <- voi_pac %>% filter(between(as.Date(timestamp),as.Date('2022-10-05'),
#                                                  as.Date('2022-10-10')))  


# make the time series data in the correct format
ts_plot_df <- voi_pac %>%
  dplyr::mutate(next_time = dplyr::lead(timestamp),
                time_diff_hr = as.numeric(difftime(next_time,
                                                   timestamp,
                                                   tz = 'UTC',
                                                   units = 'sec'))/3600,
                next_far = ifelse(time_diff_hr > 3, TRUE, FALSE),
                prev_far = ifelse(lead(next_far) == TRUE, TRUE, FALSE),
                nnet_score = as.character(ifelse(next_far == TRUE | prev_far == TRUE | 
                                                   is.na(nnet_score), 2 , nnet_score)),
                slow_speed = ifelse(speed_knots<5, TRUE, FALSE))

# make the line plot coloured by speed
line_geom <-
  geom_path(data = ts_plot_df,
            aes(x= timestamp,
                #eval(as.symbol(speed_knots)),
                y= speed_knots,
                color = factor(slow_speed),
                size = factor(slow_speed),
                group  = ssvid))
# set colours 
line_colorscale <-
  scale_color_manual('',
                     breaks = c(FALSE,TRUE),
                     values = c('#76ADAD',
                                '#E34D4E',
                                'grey85'),
                     # labels = NULL)
                     labels = c('>5 knots','< 5 knots'))
# set size 
line_sizescale <- scale_size_manual('',
                  breaks = c(TRUE,FALSE),
                  values = c(0.5,0.5,0.3),
                  # labels = NULL)
                  labels = c('>5 knots','< 5 knots'))

# time series plot of speed
time_series_plot <- ggplot() +
  line_geom +
  # point_geom +
  line_sizescale +
  line_colorscale +
  #y_axis +
  scale_x_datetime('\nDate') +
  fishwatchr::theme_gfw() +
  theme(
        legend.position = 'none',
        legend.justification = 'right',
        panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.background = element_rect(fill = '#ffffff'),
        panel.border = element_rect(fill = NA, color = '#000000'),
        plot.background = element_rect(fill = '#ffffff'))+
        # axis.text.x = element_blank(),
        # axis.title.x = element_blank()) +
  labs(y='Speed (knots)')

# make land object at default scale of  10 
land_sf <- rnaturalearth::ne_countries(scale = 10,
                                       returnclass = "sf")

# manual bounding box bounds set to +/- buf 
buf <- 0.1
bounding_box <- transform_box(xlim = c(min(ts_plot_df$lon) - buf,
                                               max(ts_plot_df$lon) + buf),
                                      ylim = c(min(ts_plot_df$lat) - buf,
                                               max(ts_plot_df$lat) + buf),
                                      output_crs = gfw_projections('Equal Earth')$proj)

# make a track object colored by speed 
track_sf <- make_track(ts_plot_df,
                       color_by = 'slow_speed')

# pull out vessel mmsi 
vessel_mmsi <- track_sf %>%
    sf::st_drop_geometry(.) %>%
    dplyr::distinct(ssvid) %>%
    dplyr::pull(ssvid)

# set land to light theme colours 
land_fill = fishwatchr::gfw_palettes$map_country_light[1]
land_color = fishwatchr::gfw_palettes$map_country_light[2]

# set grid colour 
grid_color = 'grey85'

# set vessel track geom based on speed
vessel_track_geom <-
  geom_sf(data = track_sf,
          aes(
            color = slow_speed,
            group = ssvid
          )
      )

# set geom color scale to speed too. 
vessel_track_colorscale <-
  scale_color_manual("",
                     breaks = c(FALSE, TRUE),
                     values = c(
                       "#76ADAD",
                       "#E34D4E",
                       'grey85'
                     ),
                     labels = c(
                       "> 5 knots",
                       "< 5 knots")
                     )

vessel_name <- 'LU RONG YUAN YU 715'

map <- ggplot() +
  geom_sf(
    data = land_sf,
    fill = land_fill,
    color = land_color,
    size = 0.2
  ) +
  vessel_track_geom +
  vessel_track_colorscale +
    geom_gfw_eez(colour='black', lty=2,lwd=1.2, theme ='light', proj = "+proj=eqearth +datum=WGS84 +wktext") +
  coord_sf(
    xlim = c(bounding_box$box_out[["xmin"]], bounding_box$box_out[["xmax"]]),
    ylim = c(bounding_box$box_out[["ymin"]], bounding_box$box_out[["ymax"]]),
    crs = bounding_box$out_crs
  ) +
  fishwatchr::theme_gfw_map(theme = 'light') +
  labs(title = vessel_name,
       subtitle = vessel_mmsi, 
       fill = 'Speed') +
    theme(
    # legend.position = c(1.7,0.2),
    legend.position = 'bottom',
    # legend.position = 'none',
    legend.justification = "right",
    # panel.border = element_rect(fill = NA, color = 'grey15'),
    plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "cm"),
    panel.grid.major = element_line(colour = grid_color,
                                    size = 0.1), 
    plot.title=element_text(size=10),
    plot.subtitle=element_text(size=9)
  ) 

# stacked_timeseries <- stack_timeseries(line_plot_list)
# num_components <- length(line_plot_list)
# height_ratio_list <- list(0.2, 0.3, 0.35, 0.4, 0.5)

num_components <- 1
page_layout <- patchwork::plot_layout(ncol = 1,
                                      # widths = c(1.5,1),
                                      heights = c(1 - 0.3, 0.3),
                                      guides = 'auto')
                                      # guides = 'keep')

# arrange plots on page
fishwatchr::add_little_globe(map,
                             main_box = bounding_box,
                             globe_rel_size = '0.25',
                             globe_just = 'inside',
                             globe_position = 'upperright') +
    time_series_plot +
    page_layout


# setwd('./outputs/figures')
ggsave('../outputs/figures/LU RONG YUAN YU 715_example_Pacific.png', device='png')
```




```{r}
# functions components raw 

# line_geom <-
#   geom_path(
#     data = df,
#     aes(x = timestamp,
#         y = eval(as.symbol({{var}})),
#         color = ssvid))


line_colorscale <-
  scale_color_manual('',
                     breaks = c('0','1'),
                     values = c('#76ADAD',
                                '#E34D4E',
                                'grey85'),
                     labels = c('Steaming','Fishing'))

# line_colorscale <-
#   scale_color_manual("",
#                      values = "#76ADAD",
#                      labels = 'Vessel Track')


line_sizescale <- scale_size_manual('',
                  breaks = c('0','1'),
                  values = c(0.5,0.5,0.3),
                  labels = c('Steaming','Fishing'))

# line_sizescale <- scale_size_manual('',
#                                  values = 0.5)

ggplot() +
  line_geom +
  point_geom +
  line_sizescale +
  line_colorscale +
  y_axis +
  scale_x_datetime('\nDate') +
  fishwatchr::theme_gfw() +
  theme(legend.position = 'none',
        legend.justification = 'right',
        panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.background = element_rect(fill = '#ffffff'),
        panel.border = element_rect(fill = NA, color = '#000000'),
        plot.background = element_rect(fill = '#ffffff'),
        axis.text.x = element_blank(),
        axis.title.x = element_blank())


plot_vessel_track_fish <- function(df,
                                   bounding_box_man = NA,
                                   color_fishing = TRUE,
                                   color_by = 'nnet_score',
                                   map_res = 10,
                                   theme = 'light',
                                   buffer = 0.5,
                                   add_gridlines = TRUE,
                                   gfw_proj_name = 'Equal Earth',
                                   vessel_name = 'Unspecified') {

  # specify mapping variables
  land_sf <- rnaturalearth::ne_countries(scale = map_res,
                                         returnclass = "sf")

  if (is.na(bounding_box_man)) {
    bounding_box <- fishwatchr::transform_box(xlim = c(min(df$lon) - buffer, max(df$lon) + buffer),
                                              ylim = c(min(df$lat) - buffer, max(df$lat) + buffer),
                                              output_crs = fishwatchr::gfw_projections(gfw_proj_name)$proj_string)
  } else {
    bounding_box <- bounding_box_man
  }


  # make track
  track_sf <- make_track(df,
                         color_by = color_by)

  vessel_mmsi <- track_sf %>%
    sf::st_drop_geometry(.) %>%
    dplyr::distinct(ssvid) %>%
    dplyr::pull(ssvid)

  if (theme == 'light') {
    land_fill = fishwatchr::gfw_palettes$map_country_light[1]
    land_color = fishwatchr::gfw_palettes$map_country_light[2]
    if (add_gridlines == TRUE) {
      grid_color = 'grey85'
      } else {
        grid_color = '#ffffff'
      }
  } else {
    land_fill = fishwatchr::gfw_palettes$map_country_dark[1]
    land_color = fishwatchr::gfw_palettes$map_country_dark[2]

    if (add_gridlines == TRUE) {
      grid_color = '#4F576A'
      } else {
        grid_color = '#0a1738'
      }
    }

  if (color_fishing == FALSE) {
    vessel_track_geom <-
      geom_sf(
        data = track_sf,
        aes(
          color = ssvid)
      )
    vessel_track_colorscale <-
      scale_color_manual("",
                         values = "#76ADAD",
                         labels = 'Vessel Track'
      )
  } else {
    vessel_track_geom <-
      geom_sf(data = track_sf,
              aes(
                color = get(color_by),
                group = grouping_by
              )
      )
    vessel_track_colorscale <-
      scale_color_manual("",
                         breaks = c('0', '1'),
                         values = c(
                           "#76ADAD",
                           "#E34D4E",
                           'grey85'
                         ),
                         labels = c(
                           "Steaming",
                           "Fishing")
                         )
  }

  map <- ggplot() +
    geom_sf(
      data = land_sf,
      fill = land_fill,
      color = land_color,
      size = 0.2
    ) +
    vessel_track_geom +
    vessel_track_colorscale +
    coord_sf(
      xlim = c(bounding_box$box_out[["xmin"]], bounding_box$box_out[["xmax"]]),
      ylim = c(bounding_box$box_out[["ymin"]], bounding_box$box_out[["ymax"]]),
      crs = bounding_box$out_crs
    ) +
    fishwatchr::theme_gfw_map(theme = theme) +
    theme(
      legend.position = "bottom",
      legend.justification = "right",
      # panel.border = element_rect(fill = NA, color = 'grey15'),
      plot.margin = unit(c(3, 2, 1, 1), "cm"),
      panel.grid.major = element_line(colour = grid_color,
                                      size = 0.1)
    ) +
    labs(title = vessel_name,
         subtitle = vessel_mmsi)

  return(list(plot = map,
              bbox = bounding_box))

}


```


```{r}
voi_enc_q <- readr::read_file(file = here::here("queries", ".", "voi_encounters.sql"))



voi_enc <- fishwatchr::gfw_query(query = glue::glue(voi_enc_q, 
                                              date_start = '2021-09-01',
                                              date_end = '2022-11-30', 
                                              voi = '412331284'),
                            run_query = TRUE,
                            con = con)$data

# filter encounter out that are with the second MMSI 
 

same_mmsi <- voi_enc[voi_enc$v1_ssvid == '412331284' &  voi_enc$v2_ssvid == '150400453' | 
                         voi_enc$v1_ssvid == '150400453' &  voi_enc$v2_ssvid == '412331284',]

voi_encount <- voi_enc %>% filter(!event_id %in% same_mmsi$event_id) %>% arrange(event_start)

```


